version: '3'

services:
  app:
    container_name: go_servers
    build:
      context: ./
      dockerfile: .setup/build/go/Dockerfile
    # command: sh -c "dockerize -wait tcp://rabbitmq:5672 tcp://mysql:3306 -timeout 300s -wait-retry-interval 10s"
    ports:
      - 8080:8080
      - 50051:50051
      - 8000:8000
    networks:
      - goexpert
    volumes:
      - .:/go/src
    depends_on:
      - mysql
      - rabbitmq

  mysql:
    image: 'mysql/mysql-server:8.0'
    container_name: mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: goexpert_desafio
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - .docker-volumes/mysql:/var/lib/mysql
      - .setup/build/mysql/init.sql:/docker-entrypoint-initdb.d/create-database.sql
    networks:
      - goexpert

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - goexpert

volumes:
  .docker-volumes:
    driver: local

networks:
  goexpert:
    driver: bridge
